theme: jekyll-theme-slate
title: Obrada dostavljenih podataka - Otočni rad i crni start HE Zakučac
description:  
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
include:
  - assets/css
collections:
  pages:
    output: true        # Makes pages render as actual output
    permalink: /:name/  # Creates clean URLs based on file names
header_sections:
  - label: "Crni start"
    links:
      - title: "HOPS NM"
        url: "/link1/"
      - title: "HOPS WAMS"
        url: "/link2/"
      - title: "KONČAR PROCIS"
        url: "/cs-koncar-ket/"
      - title: "GEPPERT"
        url: "/link4/"
      - title: "INEM"
        url: "/link5/"
  - label: "Otočni rad"
    links:
      - title: "HOPS NM"
        url: "/link6/"
      - title: "HOPS WAMS"
        url: "/link7/"
      - title: "KONČAR PROCIS"
        url: "/link8/"
      - title: "GEPPERT"
        url: "/link9/"
      - title: "INEM"
        url: "/link10/"