theme: jekyll-theme-slate
title: Obrada dostavljenih podataka - Otočni rad i crni start HE Zakučac
description: A simple site using a Jekyll theme
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

