theme: jekyll-theme-slate
title: Obrada dostavljenih podataka - Otočni rad i crni start HE Zakučac
description:  
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
include:
  - assets/css
collections:
  pages:
    output: true        # Makes pages render as actual output
    permalink: /:name/  # Creates clean URLs based on file names
header_sections:
  - label: "Crni start"
    links:
      - title: "HOPS NM"
        url: "/cs-hops-nm/"
      - title: "HOPS WAMS"
        url: "/cs-hops-wams/"
      - title: "KONČAR PROCIS"
        url: "/cs-koncar-ket/"
      - title: "GEPPERT"
        url: "/cs-geppert/"
      - title: "INEM"
        url: "/cs-uzbuda/"
  - label: "Otočni rad"
    links:
      - title: "HOPS NM"
        url: "/or-hops-nm/"
      - title: "HOPS WAMS"
        url: "/or-hops-wams/"
      - title: "KONČAR PROCIS"
        url: "/or-koncar-ket/"
      - title: "GEPPERT"
        url: "/or-geppert/"
      - title: "INEM"
        url: "/or-uzbuda/"
baseurl: "/admilara.github.io"
